services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/local/express/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      MONGO_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${DB_NAME}?authSource=admin
      JWT_ACCESS_SECRET_KEY: ${JWT_ACCESS_SECRET_KEY}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
      SENDER_EMAIL: ${SENDER_EMAIL}
      DOMAIN: ${DOMAIN}
      FORCE_COLOR: 1
    networks:
      - invoice
    expose:
      - "3000"

  client:
    build:
      context: ./client
      dockerfile: ./docker/local/Dockerfile
    restart: on-failure
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://nginx/api/v1
    networks:
      - invoice
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:5.0.6-focal
    container_name: invoice-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - invoice

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8083:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin@123
    networks:
      - invoice

  mailhog:
    image: mailhog/mailhog:latest
    restart: always

    ports:
      - "1026:1025"
      - "18025:8025"

    networks:
      - invoice

  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - api
      - client
    volumes:
      - static_volume:/app/staticfiles
      - pdf_volume:/app/docs
    networks:
      - invoice

networks:
  invoice:
    driver: bridge

volumes:
  mongodb_data:
  static_volume:
  pdf_volume:
